### Creating Array

The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array con‐
taining the passed data. For example, a list is a good candidate for conversion:

In [1]:
import numpy as np

In [3]:
lst1=[1,2,3,4,5]
arry=np.array(lst1)
arry

array([1, 2, 3, 4, 5])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen‐
sional array.

In [16]:
lst=[[1,2,3],[4,5,6]]

ary2=np.array(lst)
print(ary2)

[[1 2 3]
 [4 5 6]]


Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
inferred from the data. We can confirm this by inspecting the ndim and shape
attributes

In [17]:
print('dimension of array is: ',ary2.ndim)
print()
print("Shape of array is : ",ary2.shape)

dimension of array is:  2

Shape of array is :  (2, 3)


In [14]:
#what if we pass int and float

arry3=np.array([1,2,3.0,4.5])
print(arry3)  #every thing will be converted to array
print()
print(arry3.dtype)

[1.  2.  3.  4.5]

float64


In [43]:
np.array([1,2,3,4.6],dtype='int64')

array([1, 2, 3, 4], dtype=int64)

In addition to np.array, there are a number of other functions for creating new
arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
given length or shape. empty creates an array without initializing its values to any par‐
ticular value. To create a higher dimensional array with these methods, pass a tuple
for the shape:

In [21]:
arry_0=np.zeros(5)
arry_0

array([0., 0., 0., 0., 0.])

In [44]:
arry_of_0=np.zeros((2,5),dtype='int64')
arry_of_0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [26]:
#lets check the dimension and shape
print("shape",arry_of_0.shape)
print()
print("Dimensions " , arry_of_0.ndim)

shape (2, 5)

Dimensions  2


In [29]:
arry_1=np.ones((2,2,4))
arry_1  #2 dimensional with 2 rows and 4 columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
np.ones((2,3),dtype="int64")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

It’s not safe to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized “garbage” values.

In [33]:
ar=np.empty(4)
ar

array([1. , 2. , 3. , 4.5])

arange is an array-valued version of the built-in Python range function:

In [39]:
ary=np.arange(8).reshape(2,-1)
ary

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Since NumPy is
focused on numerical computing, the data type, if not specified, will in many cases be
float64 (floating point).

identity Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [50]:
np.identity(3,'int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

##### datatypes

You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

In [59]:
ary=np.arange(9)
ary.dtype

dtype('int32')

In [62]:
float_ary=ary.astype(np.float64)

float_ary.dtype

dtype('float64')

If we cast some floating-point
numbers to be of integer dtype, the decimal part will be truncated:

In [67]:
ary=np.array([2.8,-3.2,4.6,8.5,9.0])
ary.dtype

dtype('float64')

In [68]:
a=ary.astype(np.int64)
a

array([ 2, -3,  4,  8,  9], dtype=int64)

In [69]:
a.dtype

dtype('int64')

#### Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays applies the operation element-wise:


In [72]:
ar=np.array([[1,2,3],[4,5,6]])

In [73]:
ar*ar

array([[ 1,  4,  9],
       [16, 25, 36]])

In [74]:
ar-ar

array([[0, 0, 0],
       [0, 0, 0]])

Arithmetic operations with scalars propagate the scalar argument to each element in
the array:

In [75]:
1/ar

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])