### Creating Array

The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array con‐
taining the passed data. For example, a list is a good candidate for conversion:

In [77]:
import numpy as np

In [78]:
lst1=[1,2,3,4,5]
arry=np.array(lst1)
arry

array([1, 2, 3, 4, 5])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen‐
sional array.

In [79]:
lst=[[1,2,3],[4,5,6]]

ary2=np.array(lst)
print(ary2)

[[1 2 3]
 [4 5 6]]


Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
inferred from the data. We can confirm this by inspecting the ndim and shape
attributes

In [80]:
print('dimension of array is: ',ary2.ndim)
print()
print("Shape of array is : ",ary2.shape)

dimension of array is:  2

Shape of array is :  (2, 3)


In [81]:
#what if we pass int and float

arry3=np.array([1,2,3.0,4.5])
print(arry3)  #every thing will be converted to array
print()
print(arry3.dtype)

[1.  2.  3.  4.5]

float64


In [82]:
np.array([1,2,3,4.6],dtype='int64')

array([1, 2, 3, 4], dtype=int64)

In addition to np.array, there are a number of other functions for creating new
arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
given length or shape. empty creates an array without initializing its values to any par‐
ticular value. To create a higher dimensional array with these methods, pass a tuple
for the shape:

In [83]:
arry_0=np.zeros(5)
arry_0

array([0., 0., 0., 0., 0.])

In [84]:
arry_of_0=np.zeros((2,5),dtype='int64')
arry_of_0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [85]:
#lets check the dimension and shape
print("shape",arry_of_0.shape)
print()
print("Dimensions " , arry_of_0.ndim)

shape (2, 5)

Dimensions  2


In [86]:
arry_1=np.ones((2,2,4))
arry_1  #2 dimensional with 2 rows and 4 columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [87]:
np.ones((2,3),dtype="int64")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

It’s not safe to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized “garbage” values.

In [88]:
ar=np.empty(4)
ar

array([1. , 2. , 3. , 4.5])

arange is an array-valued version of the built-in Python range function:

In [89]:
ary=np.arange(8).reshape(2,-1)
ary

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Since NumPy is
focused on numerical computing, the data type, if not specified, will in many cases be
float64 (floating point).

identity Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [90]:
np.identity(3,'int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

##### datatypes

You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

In [91]:
ary=np.arange(9)
ary.dtype

dtype('int32')

In [92]:
float_ary=ary.astype(np.float64)

float_ary.dtype

dtype('float64')

If we cast some floating-point
numbers to be of integer dtype, the decimal part will be truncated:

In [93]:
ary=np.array([2.8,-3.2,4.6,8.5,9.0])
ary.dtype

dtype('float64')

In [94]:
a=ary.astype(np.int64)
a

array([ 2, -3,  4,  8,  9], dtype=int64)

In [95]:
a.dtype

dtype('int64')

#### Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays applies the operation element-wise:


In [96]:
ar=np.array([[1,2,3],[4,5,6]])

In [97]:
ar*ar

array([[ 1,  4,  9],
       [16, 25, 36]])

In [98]:
ar-ar

array([[0, 0, 0],
       [0, 0, 0]])

Arithmetic operations with scalars propagate the scalar argument to each element in
the array:

In [99]:
1/ar

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [100]:
ar**0.05

array([[1.        , 1.03526492, 1.05646731],
       [1.07177346, 1.08379839, 1.09372355]])

Comparisons between arrays of the same size yield boolean arrays:

In [101]:
ar2=np.array([[0.1,0.2,30],[0.5,40,.6]])

ar>ar2

array([[ True,  True, False],
       [ True, False,  True]])

##### Basic Indexing and Slicing.

In [102]:
#one dimensional array

ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
ar[6]  #accessing element with index 6

6

In [104]:
ar[4:8]

array([4, 5, 6, 7])

In [105]:
ar[4:6]=15
ar

array([ 0,  1,  2,  3, 15, 15,  6,  7,  8,  9])

In [106]:
array_slice=ar[4:6]
array_slice[1]=63
ar

array([ 0,  1,  2,  3, 15, 63,  6,  7,  8,  9])

In [107]:
array_slice[:]=45
ar

array([ 0,  1,  2,  3, 45, 45,  6,  7,  8,  9])

2d array

In [108]:
ar=np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
ar[1,2]

5

In [110]:
ar[:2,2]

array([2, 5])

In [111]:
ar3=np.arange(8).reshape(2,2,2)
ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
ar3[:,:,-1]

array([[1, 3],
       [5, 7]])

#### Boolean Indexing


Let’s consider an example where we have some data in an array and an array of names
with duplicates. I’m going to use here the randn function in numpy.random to generate
some random normally distributed data

In [113]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [114]:
data=np.random.randn(7,4)
data

array([[-0.64035049,  0.49755002,  2.13798602, -0.10337891],
       [-1.09737407, -0.1814863 , -1.27399843, -0.02040641],
       [ 0.44478682, -1.19125764,  0.12069507,  1.99698053],
       [-0.15451425, -0.01292585, -0.44186093, -0.16163759],
       [-0.05062559,  0.46757781, -0.87050773, -0.0055953 ],
       [ 0.45844796, -0.713678  ,  0.13173173, -0.06348184],
       [ 0.12054958,  0.67553455, -0.00420202, -0.30811561]])

Suppose each name corresponds to a row in the data array and we wanted to select
all the rows with corresponding name 'Bob'

In [115]:
data[names=='Bob']

array([[-0.64035049,  0.49755002,  2.13798602, -0.10337891],
       [-0.15451425, -0.01292585, -0.44186093, -0.16163759]])

In [116]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

To select everything but 'Bob', you can either use != or negate the condition using ~:


In [117]:
data[~(names=='Bob')]

array([[-1.09737407, -0.1814863 , -1.27399843, -0.02040641],
       [ 0.44478682, -1.19125764,  0.12069507,  1.99698053],
       [-0.05062559,  0.46757781, -0.87050773, -0.0055953 ],
       [ 0.45844796, -0.713678  ,  0.13173173, -0.06348184],
       [ 0.12054958,  0.67553455, -0.00420202, -0.30811561]])

In [118]:
data[names!='Bob']

array([[-1.09737407, -0.1814863 , -1.27399843, -0.02040641],
       [ 0.44478682, -1.19125764,  0.12069507,  1.99698053],
       [-0.05062559,  0.46757781, -0.87050773, -0.0055953 ],
       [ 0.45844796, -0.713678  ,  0.13173173, -0.06348184],
       [ 0.12054958,  0.67553455, -0.00420202, -0.30811561]])

Selecting two of the three names to combine multiple boolean conditions, use
boolean arithmetic operators like & (and) and | (or):

In [130]:
d=data[(names=='Bob')|(names=='Will')]
d

array([[-0.64035049,  0.49755002,  2.13798602, -0.10337891],
       [ 0.44478682, -1.19125764,  0.12069507,  1.99698053],
       [-0.15451425, -0.01292585, -0.44186093, -0.16163759],
       [-0.05062559,  0.46757781, -0.87050773, -0.0055953 ]])

The Python keywords and and or do not work with boolean arrays.
Use & (and) and | (or) instead.


In [61]:
data[data<0]=0
data

array([[0.11129144, 0.        , 0.        , 0.75146953],
       [0.07549448, 0.        , 0.        , 1.60438082],
       [0.69084463, 0.46534169, 0.51804392, 0.        ],
       [1.60186762, 0.42099408, 0.02183521, 0.        ],
       [0.        , 1.33053244, 0.05627081, 0.08206003],
       [0.        , 0.39971193, 1.27518786, 0.        ],
       [1.10630213, 0.        , 0.        , 0.        ]])

In [63]:
data[names=='Bob']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.07549448, 0.        , 0.        , 1.60438082],
       [0.69084463, 0.46534169, 0.51804392, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.33053244, 0.05627081, 0.08206003],
       [0.        , 0.39971193, 1.27518786, 0.        ],
       [1.10630213, 0.        , 0.        , 0.        ]])

#### Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [68]:
data=np.zeros((8,4),dtype='int64')
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [69]:
for i in range(8):
    data[i]=i
data    

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]], dtype=int64)

In [71]:
data[[4,3,7,2]]

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [7, 7, 7, 7],
       [2, 2, 2, 2]], dtype=int64)

In [72]:
data[[-3,-5,-7]]

array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]], dtype=int64)

In [73]:
a2=np.arange(32).reshape((8,4))
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
a2[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected. Regardless of
how many dimensions the array has (here, only 2), the result of fancy indexing is
always one-dimensional.

Keep in mind that fancy indexing and boolean indexing , unlike slicing, always copies the data into a new
array

In [131]:
a2[[0,3,2]][:,[0,3,2,1]]

array([[ 0,  3,  2,  1],
       [12, 15, 14, 13],
       [ 8, 11, 10,  9]])

#### 2 Universal Functions: Fast Element-Wise Array Functions

In [134]:
x=np.random.randn(8)
x

array([ 0.45811454,  0.08323857, -0.42643212, -0.56814565,  0.20083789,
        0.76668857, -0.89687532,  0.03473304])

In [135]:
np.exp(x)

array([1.58109009, 1.08680105, 0.65283418, 0.56657509, 1.22242659,
       2.15262617, 0.40784205, 1.03534328])

In [136]:
np.sqrt(x)

C:\Users\shraj\AppData\Local\Temp/ipykernel_6724/393099422.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(x)


array([0.67684159, 0.28851095,        nan,        nan, 0.44814941,
       0.87560754,        nan, 0.18636803])

These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays
(thus, binary ufuncs) and return a single array as the result:


In [137]:
y=np.random.randn(8)


In [138]:
np.add(x,y)

array([ 1.24455471,  1.50387865,  0.27608428, -0.15814274,  0.09613887,
       -0.25827066, -0.97998865, -0.38412822])

In [140]:
np.maximum(x,y)

array([ 0.78644018,  1.42064008,  0.7025164 ,  0.41000292,  0.20083789,
        0.76668857, -0.08311333,  0.03473304])

#### Expressing Conditional Logic as Array Operations

The numpy.where function is a vectorized version of the ternary expression x if con
dition else y. Suppose we had a boolean array and two arrays of values:

In [155]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

y. Suppose you had a matrix of randomly generated
data and you wanted to replace all positive values with 2 and all negative values with
–2. This is very easy to do with np.where

In [156]:
a=np.random.randn(4,4)
a

array([[ 0.48520107, -1.31466936,  0.15583197,  1.2435949 ],
       [-0.3618754 ,  0.85071504,  0.60081845, -0.47520166],
       [ 0.58437641,  1.06576815, -0.27870026,  1.22294912],
       [-0.84272985,  0.63467121, -0.25750858, -1.28816361]])

In [160]:
np.where(a>0,2,-2)

array([[ 2, -2,  2,  2],
       [-2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [-2,  2, -2, -2]])

You can combine scalars and arrays when using np.where. For example, I can replace
all positive values in arr with the constant 2 like so:

In [163]:
np.where(a>0,2,a)

array([[ 2.        , -1.31466936,  2.        ,  2.        ],
       [-0.3618754 ,  2.        ,  2.        , -0.47520166],
       [ 2.        ,  2.        , -0.27870026,  2.        ],
       [-0.84272985,  2.        , -0.25750858, -1.28816361]])

#### Mathematical and Statistical Methods

In [164]:
a=np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [165]:
np.sum(a)

28

In [166]:
np.sum(a,axis=1)

array([ 6, 22])

In [168]:
a.sum(0)

array([ 4,  6,  8, 10])

In [169]:
a.mean(0)

array([2., 3., 4., 5.])

In [170]:
a.mean()

3.5

Here, arr.mean(1) means “compute mean across the columns” where arr.sum(0)
means “compute sum down the rows.”

In multidimensional arrays, accumulation functions like cumsum return an array of
the same size, but with the partial aggregates computed along the indicated axis
according to each lower dimensional slice:

In [173]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
a.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [175]:
a.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [176]:
a.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [181]:
ar=np.random.randn(3,3)
ar

array([[ 0.66473953, -0.04253694, -0.3329496 ],
       [-0.64623994, -1.53341657,  0.26277593],
       [ 2.12662534, -0.6718784 ,  0.69050572]])

In [182]:
ar.argmin()

4

In [183]:
ar.argmin(axis=1)

array([2, 1, 1], dtype=int64)

In [185]:
ar.argmin(axis=0)

array([[-0.64623994, -1.53341657,  0.26277593],
       [-0.64623994, -1.53341657,  0.26277593],
       [ 0.66473953, -0.04253694, -0.3329496 ]])

#### Methods for Boolean Arrays

In [187]:
a=np.random.randn(4,4)
a

array([[-1.06273411, -0.54519899, -0.76419365, -1.2283753 ],
       [-0.4574742 ,  0.43334907,  0.2388155 , -1.75622163],
       [ 2.34425109, -0.02006801,  0.97813023,  0.17930856],
       [-1.15080524,  0.27015542, -0.62842757,  0.25150465]])

In [188]:
#to find number of positive values

(a>0).sum()

7

There are two additional methods, any and all, useful especially for boolean arrays.
any tests whether one or more values in an array is True, while all checks if every
value is True:

In [189]:
(a>0).all()

False

In [190]:
(a>0).any()

True